---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update Cache
      apt: 
        update_cache: yes
        cache_valid_time: 86400
  tags: [ 'packages' ]

- include: control.yml
- include: webserver.yml
- include: database.yml
- include: loadbalancer.yml