---
- hosts: all, !control  
  become: yes
  tasks:
 #   - name: Installing python
  #    yum: name=python state=present update_cache=yes

  #  - name: update system
   #   command: yum update

#    - name: Installing vim
 #     yum: name=vim state=present

  #  - name: Installing git
   #   yum: name=git state=present

    - name: Open up port 80
      command: firewall-cmd --add-service=http --permanent 

    - name: Confirm
      command: firewall-cmd --reload                